const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUEST';
const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
const FETCH_ARTISTS_FAILURE = 'FETCH_ARTISTS_FAILURE';

const CHECK_ARTISTS = 'CHECK_ARTISTS';
const UNCHECK_ARTISTS = 'UNCHECK_ARTISTS';

const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

const ADD_ARTIST_REQUEST = 'ADD_ARTIST_REQUEST';
const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
const ADD_ARTIST_FAILURE = 'ADD_ARTIST_FAILURE';

const OPEN_ARTIST_ADD_DIALOG = 'OPEN_ARTIST_ADD_DIALOG';
const CLOSE_ARTIST_ADD_DIALOG = 'CLOSE_ARTIST_ADD_DIALOG';

const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

const SWITCH_ARTIST_FILTER = 'SWITCH_ARTIST_FILTER';

const BULK_ARTIST_EDIT_REQUEST = 'BULK_ARTIST_EDIT_REQUEST';
const BULK_ARTIST_EDIT_FAILURE = 'BULK_ARTIST_EDIT_FAILURE';
const BULK_ARTIST_EDIT_SUCCESS = 'BULK_ARTIST_EDIT_SUCCESS';

const GET_ARTIST_INFO_REQUEST = 'GET_ARTIST_INFO_REQUEST';
const GET_ARTIST_INFO_SUCCESS = 'GET_ARTIST_INFO_SUCCESS';
const GET_ARTIST_INFO_FAILURE = 'GET_ARTIST_INFO_FAILURE';

const PATCH_ARTIST_REQUEST = 'PATCH_ARTIST_REQUEST';
const PATCH_ARTIST_SUCCESS = 'PATCH_ARTIST_SUCCESS';
const PATCH_ARTIST_FAILURE = 'PATCH_ARTIST_FAILURE';

const DELETE_ARTIST = 'DELETE_ARTIST';

const EDITOR_STATE_CHANGE = 'EDITOR_STATE_CHANGE';

const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

const ARTIST_DOWNLOAD_PATH_REQUEST = 'ARTIST_DOWNLOAD_PATH_REQUEST';
const ARTIST_DOWNLOAD_PATH_SUCCESS = 'ARTIST_DOWNLOAD_PATH_SUCCESS';
const ARTIST_DOWNLOAD_PATH_FAILURE = 'ARTIST_DOWNLOAD_PATH_FAILURE';
const OPEN_ARTIST_DOWNLOAD_DIALOG = 'OPEN_ARTIST_DOWNLOAD_DIALOG';
const CLOSE_ARTIST_DOWNLOAD_DIALOG = 'CLOSE_ARTIST_DOWNLOAD_DIALOG';

export {
  FETCH_ARTISTS_REQUEST,
  FETCH_ARTISTS_SUCCESS,
  FETCH_ARTISTS_FAILURE,
  CHECK_ARTISTS,
  UNCHECK_ARTISTS,
  UPDATE_SEARCH_FILTER,
  ADD_ARTIST_REQUEST,
  ADD_ARTIST_SUCCESS,
  ADD_ARTIST_FAILURE,
  OPEN_ARTIST_ADD_DIALOG,
  CLOSE_ARTIST_ADD_DIALOG,
  FETCH_GENRES_REQUEST,
  FETCH_GENRES_SUCCESS,
  FETCH_GENRES_FAILURE,
  SWITCH_ARTIST_FILTER,
  BULK_ARTIST_EDIT_FAILURE,
  BULK_ARTIST_EDIT_SUCCESS,
  BULK_ARTIST_EDIT_REQUEST,
  GET_ARTIST_INFO_REQUEST,
  GET_ARTIST_INFO_SUCCESS,
  GET_ARTIST_INFO_FAILURE,
  PATCH_ARTIST_REQUEST,
  PATCH_ARTIST_SUCCESS,
  PATCH_ARTIST_FAILURE,
  DELETE_ARTIST,
  EDITOR_STATE_CHANGE,
  FETCH_CATEGORIES_FAILURE,
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_SUCCESS,
  ARTIST_DOWNLOAD_PATH_REQUEST,
  ARTIST_DOWNLOAD_PATH_SUCCESS,
  ARTIST_DOWNLOAD_PATH_FAILURE,
  OPEN_ARTIST_DOWNLOAD_DIALOG,
  CLOSE_ARTIST_DOWNLOAD_DIALOG,
};
