const FETCH_ACCOUNT_REQUEST = 'FETCH_ACCOUNT_REQUEST';
const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
const FETCH_ACCOUNT_FAILURE = 'FETCH_ACCOUNT_FAILURE';

const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';

const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';

const TRANSFER_STATUS_REQUEST = 'TRANSFER_STATUS_REQUEST';
const TRANSFER_STATUS_SUCCESS = 'TRANSFER_STATUS_SUCCESS';
const TRANSFER_STATUS_FAILURE = 'TRANSFER_STATUS_FAILURE';

export {
  FETCH_ACCOUNT_REQUEST,
  FETCH_ACCOUNT_SUCCESS,
  FETCH_ACCOUNT_FAILURE,
  UPDATE_ACCOUNT_REQUEST,
  UPDATE_ACCOUNT_SUCCESS,
  UPDATE_ACCOUNT_FAILURE,
  REMOVE_ACCOUNT,
  TRANSFER_STATUS_REQUEST,
  TRANSFER_STATUS_SUCCESS,
  TRANSFER_STATUS_FAILURE
};
