export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const OPEN_USER_DELETE_DIALOG = 'OPEN_USER_DELETE_DIALOG';
export const CLOSE_USER_DELETE_DIALOG = 'CLOSE_USER_DELETE_DIALOG';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const OPEN_USER_ADD_DIALOG = 'OPEN_USER_ADD_DIALOG';
export const CLOSE_USER_ADD_DIALOG = 'CLOSE_USER_ADD_DIALOG';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const OPEN_USER_SUSPEND_DIALOG = 'OPEN_USER_SUSPEND_DIALOG';
export const CLOSE_USER_SUSPEND_DIALOG = 'CLOSE_USER_SUSPEND_DIALOG';

export const OPEN_USER_EDIT_DIALOG = 'OPEN_USER_EDIT_DIALOG';
export const CLOSE_USER_EDIT_DIALOG = 'CLOSE_USER_EDIT_DIALOG';

export const OPEN_USER_RESET_PASSWORD_DIALOG = 'OPEN_USER_RESET_PASSWORD_DIALOG';
export const CLOSE_USER_RESET_PASSWORD_DIALOG = 'CLOSE_USER_RESET_PASSWORD_DIALOG';

export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
export const SWITCH_USERS_FILTER = 'SWITCH_USERS_FILTER';

export const USERS_DOWNLOAD_PATH_REQUEST = 'USERS_DOWNLOAD_PATH_REQUEST';
export const USERS_DOWNLOAD_PATH_SUCCESS = 'USERS_DOWNLOAD_PATH_SUCCESS';
export const USERS_DOWNLOAD_PATH_FAILURE = 'USERS_DOWNLOAD_PATH_FAILURE';

export const OPEN_USER_DOWNLOAD_DIALOG = 'OPEN_USER_DOWNLOAD_DIALOG';
export const CLOSE_USER_DOWNLOAD_DIALOG = 'CLOSE_USER_DOWNLOAD_DIALOG';